[window]
padding = { x = 8, y = 8 }
decorations = "Buttonless"     # Options: Full | None | Transparent | Buttonless
opacity = 1.0
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.5
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 500
thickness = 0.15

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]

# -----------------------------
#       Gruvbox Dark Theme
# -----------------------------
[colors.primary]
background = "#282828" # hard contrast: "#1d2021", soft contrast: "#32302f"
foreground = "#ebdbb2"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.selection]
text       = "CellForeground"
background = "#458588"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

